version: "3"
services:
  broker1:
    image: ${USER}/local/kafka:2.8.0
    build: .
    restart: always
    hostname: kafka1.local.private
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo1.local.private:2181,zoo2.local.private:2181,zoo3.local.private:2181"
      KAFKA_BROKER_ID: 1
    networks:
      net:
        ipv4_address: "10.14.14.40"
    depends_on: [zoo1, zoo2, zoo3] 
  # kafka_2:
  # kafka_3:
  zoo1:
    image: zookeeper:3.7.0
    restart: always
    hostname: zoo1.local.private
    ports:
      - 2181:2181
      - 8080:8080
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1.local.private:2888:3888;2181 server.2=zoo2.local.private:2888:3888;2181 server3=zoo3.local.private:2888:3888;2181
    networks:
      net:
        ipv4_address: "10.14.14.10"
  zoo2:
    image: zookeeper:3.7.0
    restart: always
    hostname: zoo2.local.private
    ports:
      - 2182:2181
      - 8081:8080
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1.local.private:2888:3888;2181 server.2=zoo2.local.private:2888:3888;2181 server3=zoo3.local.private:2888:3888;2181
    networks:
      net:
        ipv4_address: "10.14.14.20"
  zoo3:
    image: zookeeper:3.7.0
    restart: always
    hostname: zoo3.local.private
    ports:
      - 2183:2181
      - 8082:8080
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1.local.private:2888:3888;2181 server.2=zoo2.local.private:2888:3888;2181 server3=zoo3.local.private:2888:3888;2181
    networks:
      net:
        ipv4_address: "10.14.14.30"

networks:
    net:
      ipam:
        driver: default
        config:
          - subnet: "10.14.14.0/24"
