- hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - 'vars.yml'
  tasks:
    - name: Disable remote host key checking
      lineinfile:
        path: /etc/ansible/ansible.cfg
        line: 'host_key_checking = False'
        regex: '^#host_key_checking = False'
        state: present

    - name: Create Zookeeper hosts block
      blockinfile:
        path: /etc/ansible/hosts
        block: '{{ hosts_block }}'