- hosts: zookeeper
  gather_facts: yes
  become: yes
  vars_files:
    - "vars.yml"
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: true

    - name: Install java-common
      apt:
        name: java-common
        state: present

    - name: Install supervisord
      pip:
        name: supervisor
        state: present

    - name: Install Corretto
      apt:
        deb: '{{ corretto_url }}'
        state: present
      
    - name: Download Zookeeper
      get_url:
        url: '{{ zookeeper_url }}'
        dest: /tmp/

    - name: Install Zookeeper
      unarchive:
        src: '/tmp/{{ zookeeper_archive }}'
        dest: /usr/local/bin/
        remote_src: yes

    - name: Symlink Zookeeper directory
      file:
        src: '/usr/local/bin/apache-zookeeper-{{ zookeeper_release }}-bin'
        dest: /usr/local/bin/zookeeper
        state: link

    - name: Create Zookeeper config directory
      file:
        path: /etc/zookeeper/
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Template the Zookeeper config file
      template:
        src: templates/zookeeper-conf.j2
        dest: /etc/zookeeper/zoo.cfg
        owner: root
        group: root
        mode: 0644
        
    - name: Template the Zookeeper myid file
      template:
        src: templates/zookeeper-myid.j2
        dest: "{{zookeeper_data_dir}}/myid"

    - name: Sync the systemd zookeeper unit file
      copy:
        src: templates/zookeeper-unit.j2
        dest: /usr/lib/systemd/system/zookeeper.service
      notify:
        - restart-zookeeper

    - name: Start Zookeeper service
      systemd:
        name: zookeeper
        state: started
        daemon-reload: True

  handlers:
    - name: Restart zookeeper
      systemd:
        name: zookeeper
        state: restarted
        daemon-reload: true
      listen:
        - restart-zookeeper